[{'bgcolor': u'#E5E5E5',
  'components': [{'left': '10',
                  'name': 'field1',
                  'top': '10',
                  'type': 'TextBox',
                  'value': u'Hello gui2py',
                  'width': '288'},
                 {'bgcolor': u'#E5E5E5',
                  'components': [{'id': 210,
                                  'left': '187',
                                  'name': 'mybutton',
                                  'top': '24',
                                  'type': 'Button'},
                                 {'id': 162,
                                  'left': '21',
                                  'name': 'label_162',
                                  'top': '34',
                                  'type': 'Label'}],
                  'fgcolor': u'#4C4C4C',
                  'height': '74',
                  'id': 173,
                  'image': '',
                  'label': u'panel!',
                  'left': '16',
                  'name': 'mypanel',
                  'top': '50',
                  'type': 'Panel',
                  'width': '282'}],
  'fgcolor': u'#4C4C4C',
  'height': '154px',
  'image': '',
  'left': '647',
  'menubar': [{'items': [{'id': 156,
                          'label': u'&About\tAlt+a',
                          'name': u'about',
                          'type': 'MenuItem'},
                         {'label': u'E&xit\tAlt+X',
                          'name': u'exit',
                          'type': 'MenuItem'}],
               'label': u'&File',
               'name': u'file',
               'type': 'Menu'}],
  'name': 'bgMin',
  'resizable': True,
  'title': u'Minimal gui2py resource app',
  'top': '123',
  'type': 'Window',
  'width': '315px'}]