#----------------------------------------------------------------------
# This file was generated by /usr/local/lib/python2.7/dist-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
button = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAIhJ"
    "REFUOI3l1EsOhCAQBNAq4DR1b67UXMb5LCYajTjTaruY2KtuCI9fgEwZ0ZHCxavQAgDPx/CK"
    "wEiCKbOMDa21U2Ctdcr/50w3UUmQtKh7uRuVBDODma2Ase/QSr9N9it2ob2Vn0a9cOk1zgd6"
    "tutCe9i8Dr0ob1z3oQDLtxuCkgwDP96tf/43oF4rp3HCLawAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
label = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAANBJ"
    "REFUOI3VlN0OgyAMhU9bIPt5/2ddwizdhcGgA+0yk2XnRpHy9bSARCw4W3w68edQCbBToRJg"
    "ms0N9juFINnVFXsIjYUXd5keLreH0JLK/FKfDrnKn7JiyrqMj9zuQq2oAQCxELP/9O1GhiS4"
    "Xe7LuHXMNHZLo2tqRS0kgU4goF9ynXNDPbuszwIQv4G75VegaW+2iYv97oW9RcVAmPoJgbnH"
    "IYlt2/CW6pM7HlK/dStoPULVRU+971sjK2iMcdXHNkldPHLXarj73+h//vwvGetOd6weON0A"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
textbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAALhJ"
    "REFUOI3VlVsOgyAQRc9YVuMK2+KnbnFYzvWjsUGL1Fb60ZtMwvOQO0PArLvQWl1zIhDut6ta"
    "AsdxJABM09QE6O5AZl/S6VjUJKdmtuofhm431vST6hehZvaMXCml4vhbqJnh7kjC3VeAvu+R"
    "RIyxDo4xCtCelrntmry/tN1dkhT27J9R1X5+905Bj2gYhur8i31Ju/bz8ZqLYk5LGz5JRZPL"
    "vz0wwON1SSm14ANg+rbENejffCczVf6vRkw/o+MAAAAASUVORK5CYII=")


#----------------------------------------------------------------------
checkbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAI9J"
    "REFUOI3V1NEKgCAMBdA77a+tKPq0wn6qslexdFvYgxd8mXDQwUZkLGrHVBebQru0sExz0ABu"
    "cDC2oyIKAP3Yi0C/+td69vshBPbk8qmnRFS8V6McyKIpIAFZNIZisNRPEaoFWTQFJCCLxpAU"
    "FKFaEMhMlF899m1XQXEo3afXeeieBTxm/4HWSDv79Bf0BmNuQIvbuvzSAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
combobox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAKpJ"
    "REFUOI3F1UEOgjAQheG/6KUgupBzERdYroWLmuFYdWEiCK1MscS3arr4Ms1MW2OKA7lTZBcB"
    "Y1vrc6NHgObaZAPFyQsF8H5Z8PAYksDqXAGMaCzlqVSB3a17r1dRSK94l+7vgqqOD2MT5rGt"
    "pb7UH3vqSsWJCkxC53AMhITjT+H+3kdB2Niob+BmdC3/Ganp9cuCxmZThYqT4P0OzaYmxofe"
    "vB9j9vijnggYMJoIaBN+AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
listbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAANNJ"
    "REFUOI21lUESgyAMRX/aXgrHLuq16nRh8WQy5FjpgkFFUFTs3ziJk/D4RiC63XG1SHdazha3"
    "nzb9QndazgpAENvBCgB5ROjUZwlF3kHcf11N82quIwUgAM6TLinZMOxgg1zUdFmUU/Wsolyx"
    "pyICNgxVK7Bht0ipp3aw45f3uWJPPaF/jtvfs+W1RecNVa2mplskucarpFskOa2SzumOeErU"
    "7iM9OqdEFOUumVMvP6fFpA7E0frftXhOAUB3OoiLSdnwdOTNm6bM3qvUgUL/uKN+htVDI3hs"
    "0BUAAAAASUVORK5CYII=")


#----------------------------------------------------------------------
custom = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAShJ"
    "REFUOI21lT9uwjAUhz8n6VAkGDpUieAO5hZwi3CFZGrL3pYluQJbrpDcgizpllAJpEwMrQRD"
    "I7lDFfpHAqxifpIX6/nT954lWwjLxnQcgIf7O2UK+Pj0LBCWzXQ6VcBZSymlyrJUwrK/TNsU"
    "RWHE1jJC+RPndAl00xSAxvPYSXketJumDMLw195WStZxTOO6B88dbN+p6z1wmSS8FAWrKKKT"
    "5/SD4Kjp0Zmuoohlkuxbfh+PAejk+VHowfYb191D2rSG2xNz1b79fhDQyzI+XJd1HP/P9Gdu"
    "ZzN6WcZWSl6T5GS9lulVXQOw8X2dcj3TzWTC22jEbjjUgmqZ3sznDMKQ68VCC6pl2ho2nmcO"
    "uvF90JwnXPpBUcrYO/0NrarKGFRc4o/6BMuAaAwB5rcdAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
frame = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAIhJ"
    "REFUOI3t1LENAyEMheHfd9TswUwMQhIo41FY6QZhAacISlKkSnzFSWfJMjSf9GTJIsuKdy3u"
    "IhBu14t5gqUUAoAqGAoGIvVnsFaIMb7jixky32b3V3/+v9W2ZUDnnFat1TW+qj7j55xJKf0N"
    "ttaAnbZ/oid6BDQA9N591TGGAa4th7n8u6APH3E8/05PRJIAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
menubar = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAxNJ"
    "REFUOI3VlU9rY1UYxn/nnPsn6U2am0Ro6HTGUT9LV4o7xaII3VvQ6RcQYRh00ZVQLFNQuiz0"
    "E/QDtFutS20LJTM1TXpvbG5Ocu89r4u0M1N0HAdm4wtndeDH+zzv856jlDa86dJvnAigtMFm"
    "Y5G8EHGFFMVUnJTipJRe/0JERMbDTKSU2XEiIiKDwWB2Nx7LTWVZJoB4AL4xHP/2O4XLKRXY"
    "MieOY4wx/PzLr4SeT6gDsvEVyvdQBqIo4uzsjGq1CkC32+Xg4OC5fO37TCYTRIR6vY4xhiRJ"
    "2NjYII5j8jxnbm6OOI7Z3t4miiKSJKHZbCIibG1tsbCwQK/Xu+1pEASEYcjx8TGdToc4jgFw"
    "ztFut+l2uzjnaDabKKXwPA9rLdZanHOUZUmj0XgBWpY45yiKgqWlJY6OjhARfN8HYDweU6vV"
    "6Pf7pGmKc440TSnLEmstnU4HrTVJkgDgAWAMYRiydO8Oyve4c/8ek8mERw8fYbMpUbXCgy8e"
    "sHR3Ec/zyPOc/f19jDGkaUqWZRhjnjXh3cjv9XrcffdtTk9PuZqMmZ+f53x6TmEdjVqdVqvF"
    "8vIyXiUEYGVlhX6/T61WY2FhgZOTk2fyPYDcWg4PD3nnvfs459jZ2UEpRVEURGGdTz76GM/z"
    "2N3dRfkek9wSBAFaa7TWXFxc0Gw2GQ6Hs5gqbdCulGpQ4U874un5U55c/EGj0cBaS6ArBMbj"
    "p8c/8s3Dr3EoRLmX516pWadOGzUqcsZXV5IkCXt7e1SrVYbDIa35t/jw/Q8oyxLf+Fgp1L8t"
    "orzoKUAYhrTbbVZXV0nTFGMMHgHtVpssy8jLHLR6KfCmbkH1dei//2GTxcVFrLVMRjnrX34F"
    "QCWoMComrwfl2vj19XUuLy+p1WpMs4KyLFFKISKvBP4dCogIm5ubwGybAl3h808/o1KpMM2n"
    "/+lduwUdDYcYY1hbW2MwGBBFERSa8dWIer2OVhp4+eT/ERo15nn83beMJ5agWiEwAWVe0Irb"
    "dJ+cUUoJ6rUHFSjBCYC6tk/JTPFz1Kuh6n/znfwFbR9/PubQUncAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
image = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAQHSURBVHjaYtx+7hMDBPxnYPjx"
    "iYGR4W+ZrARPKTMTIwMDQobh129Ghk9ffzDcvn1/05evn1JZWdj+ffn+mwEggFj+H21mYASp"
    "YGVl+K8Zw8DCJ8qnoSAkgtAOAZ9/MjA8ev6FQUdbPenWnXvf3r17nwsSBwgg5ijGYwwMd0D4"
    "MMPf2+sZWKT1rRTU1J3QDfgDtOTT198MgjwsDGoqsmbPX33g+Pj5216AAGJhYIeqAOr4+/AZ"
    "2689tdJPOB8w/Hh5n4GZS4CBiVucQVTbnoFLSoOBm5uL4cnTpwzcHCwMvLx8FQwv3v8ECCAW"
    "sB+Bpv/9zRDGpyScxaukZnL66isGBiZxBnUuVoZ/988wPD62hoFL1pBBNqCegZ2bn+HmnYcM"
    "X77/Yfj3n6EKIAAAQQC+/wT+/gAAAgEAhiBHTXkpWogAzvYiAKzDBwD9AwAAL/bjAF5R9gDt"
    "4NMA5raaAOeRXAAnZKIAFRUVAA/5+gDy8fD2AgBBAL7/A1knAGYRJSOJAAkQuvXjzOrs/Aod"
    "g7YUANDWAAAg97cAzxifAL8K3gD7HiMAKNrbANvY1QAULUkABgQAAOzu8PkCAEEAvv8EDR0W"
    "eQ8lJ/jInraFAQUAJEh/GDmVQfYA3trwAGE99ABO4sMA0gviAFPxLwB7SU4AoZWhAAFIcgAL"
    "DxcABAQDAAKIhUtcREYr2JuFi495LTPjf2ZJcSaGWJnjDAwaPxgYgHHf+0aD4dhTbga/PxIM"
    "bMK3GATYvjN8f/2AQVRKnoGViZkBIAAAQQC+/wTl1d67FcS7SSE1JhQAAfoAAOjhAAD39AAA"
    "+vcAAPn3AEP/+ABD3xgA/Qg9APLZtwAA9fEAAP/+AAYGAQACAwEAAojly/sf8fsmbfATkBZI"
    "MbBXt1BSFoQo+vkNmDK/Mvz985Xh3fZnDCIPHzG8ZnrM8NLoH4OimBQDEyjmGRkZAAKICeiK"
    "18CYmPv4zgevLYtPLnt0+QEDwz+g7d+Arvj+nYHp50+Gf+ofGB7yPGB4rfiL4Y+oEoOQhALI"
    "EUADGBgAAogJnIaAJDs7w/tvPxmydu+4feH3+/cQQ75/ZWD89I1B3PAvg3z6X4a7ogwMivZp"
    "DBzcHEBd/8CpDyCAmP7/ATKB4fXuI9jrH18ziOzYfvgjw7Pbrxh+fvjI8P/TD4b3r/8xrAWm"
    "9g9yjgxGAdkMv378huQwIAAIIBYWUREGQedIBjYGToa/v/4xiGha/VYU/MFwesd0hv8vbzMA"
    "0yLD298cDILuUQwR8fUMTECnfv/2j4GdlQkYjSzsAAHEuO3AVQZmfmlgamQC++nPr+9lv368"
    "L/355RPDly9fGP7+ZQApZOAWFANa8IPhFyhMgGmfGRh4T56/+gQQYADZtXRJ8ecNFwAAAABJ"
    "RU5ErkJggg==")

#----------------------------------------------------------------------
gauge = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAHRJ"
    "REFUOI3t0jsOgCAQBNBZ4DLcUM2WLHBCWi7irzBiY2zchujUm5dJZomMhXaMuvijDgCmcdg0"
    "sJgyNRQAQgi3h8wMEUEp5RH03iOmfDU9U2t92fVIP0P1g7ahmFkfFRE1lMhYrMus8vzGOmqo"
    "dvpZ/+PoDjvxFwVp8EfYAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
html = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAL2SURBVDjLVdNNaBx1GMfx78zO"
    "7Lu765qQWIPteqiH+IKCjTmkClIVPHi0pVDSXBT0sGhLUOvJl0OL4AuVBC+CLXpoD1KqweBB"
    "WFFajOChSTU20q2h6e66nX2Znfm/ejCJ8Qff6+fy8DjWWgCmz9f3AR/cV0pPhtIQSoM0hoEy"
    "AdAFmoAG2kAL+Bz41mNzRqmJh0fzk689MczO9YUphsIU25EeExK6sebPZo9v/ugfAKo7gZFC"
    "0gGgflvjOw6eAwkPUr7LvSmXhOviJ+CRsQy7irnyp5fW33e3AC1loWQilIGucAgkdDoRQQRB"
    "BK0B3OppAF4/e53JSo4HhvzhbSAfBiP7v5pHHZ2mH2kqJ2cZ+uxjwqBPNzb0IstAgAEc3eGn"
    "a22WrgfrLoA4Ol2eXfrimZw3QDoeYWyRePh0GZ0/RdTu0o8NfWnAwkYn5sPF1Y4WYtoVR44c"
    "NGH01+iwXzT1FvVj76CApUNVxI2ApNNn77EZUrXviZSDsaB9jRKicv7lxxZdM4jm433jabO0"
    "Asdn6eTLOC7oQpnfX3gFfrmKnBjnnrmTuFJiLag4RotYA7gmHLyY+LoWmcounBNvYm81cLEk"
    "gyaVuXdRe+7GuVijPlPFSfpIren1Q6WE6AC42YsXvjy9e//EtdXbyHyKyqszYOH+946TKHiE"
    "bcOVuXMEUwfI+NDqxahYbCy89awFcAEWhvaKj6YO48WQaDTAcXGbDcIA1k6cQuaKYCHruTTa"
    "A7SI17eu501Vzw4Bbz84OU6veobvlgW5rubHTy6Q9i2+B8nEvxWysFoPUUJsbANaiKeA535e"
    "XqM98OjFFqktsXQQyqC0wVhLuVjkpadHudkK0UI0/gOkfPT5Jx/KvHH48f/9gLYgtUUowMLp"
    "hXWyPnR7IVrK1k5g7WYz4MziMqV8hlIhTSmXophLcUc2SSrpkvJcDk2NkPKg8XcXLeWNbcAo"
    "da52eWWsdnllN3DXZnduVkwnfT+d9inkMpQKWX69Wv8N+GEL+AdfSH+n2ppttwAAAABJRU5E"
    "rkJggg==")

