#----------------------------------------------------------------------
# This file was generated by /usr/local/lib/python2.7/dist-packages/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
button = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAIhJ"
    "REFUOI3l1EsOhCAQBNAq4DR1b67UXMb5LCYajTjTaruY2KtuCI9fgEwZ0ZHCxavQAgDPx/CK"
    "wEiCKbOMDa21U2Ctdcr/50w3UUmQtKh7uRuVBDODma2Ase/QSr9N9it2ob2Vn0a9cOk1zgd6"
    "tutCe9i8Dr0ob1z3oQDLtxuCkgwDP96tf/43oF4rp3HCLawAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
label = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAANBJ"
    "REFUOI3VlN0OgyAMhU9bIPt5/2ddwizdhcGgA+0yk2XnRpHy9bSARCw4W3w68edQCbBToRJg"
    "ms0N9juFINnVFXsIjYUXd5keLreH0JLK/FKfDrnKn7JiyrqMj9zuQq2oAQCxELP/9O1GhiS4"
    "Xe7LuHXMNHZLo2tqRS0kgU4goF9ynXNDPbuszwIQv4G75VegaW+2iYv97oW9RcVAmPoJgbnH"
    "IYlt2/CW6pM7HlK/dStoPULVRU+971sjK2iMcdXHNkldPHLXarj73+h//vwvGetOd6weON0A"
    "AAAASUVORK5CYII=")

#----------------------------------------------------------------------
textbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAALhJ"
    "REFUOI3VlVsOgyAQRc9YVuMK2+KnbnFYzvWjsUGL1Fb60ZtMwvOQO0PArLvQWl1zIhDut6ta"
    "AsdxJABM09QE6O5AZl/S6VjUJKdmtuofhm431vST6hehZvaMXCml4vhbqJnh7kjC3VeAvu+R"
    "RIyxDo4xCtCelrntmry/tN1dkhT27J9R1X5+905Bj2gYhur8i31Ju/bz8ZqLYk5LGz5JRZPL"
    "vz0wwON1SSm14ANg+rbENejffCczVf6vRkw/o+MAAAAASUVORK5CYII=")


#----------------------------------------------------------------------
checkbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAI9J"
    "REFUOI3V1NEKgCAMBdA77a+tKPq0wn6qslexdFvYgxd8mXDQwUZkLGrHVBebQru0sExz0ABu"
    "cDC2oyIKAP3Yi0C/+td69vshBPbk8qmnRFS8V6McyKIpIAFZNIZisNRPEaoFWTQFJCCLxpAU"
    "FKFaEMhMlF899m1XQXEo3afXeeieBTxm/4HWSDv79Bf0BmNuQIvbuvzSAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
combobox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAKpJ"
    "REFUOI3F1UEOgjAQheG/6KUgupBzERdYroWLmuFYdWEiCK1MscS3arr4Ms1MW2OKA7lTZBcB"
    "Y1vrc6NHgObaZAPFyQsF8H5Z8PAYksDqXAGMaCzlqVSB3a17r1dRSK94l+7vgqqOD2MT5rGt"
    "pb7UH3vqSsWJCkxC53AMhITjT+H+3kdB2Niob+BmdC3/Ganp9cuCxmZThYqT4P0OzaYmxofe"
    "vB9j9vijnggYMJoIaBN+AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
listbox = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAANNJ"
    "REFUOI21lUESgyAMRX/aXgrHLuq16nRh8WQy5FjpgkFFUFTs3ziJk/D4RiC63XG1SHdazha3"
    "nzb9QndazgpAENvBCgB5ROjUZwlF3kHcf11N82quIwUgAM6TLinZMOxgg1zUdFmUU/Wsolyx"
    "pyICNgxVK7Bht0ipp3aw45f3uWJPPaF/jtvfs+W1RecNVa2mplskucarpFskOa2SzumOeErU"
    "7iM9OqdEFOUumVMvP6fFpA7E0frftXhOAUB3OoiLSdnwdOTNm6bM3qvUgUL/uKN+htVDI3hs"
    "0BUAAAAASUVORK5CYII=")


#----------------------------------------------------------------------
custom = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAShJ"
    "REFUOI21lT9uwjAUhz8n6VAkGDpUieAO5hZwi3CFZGrL3pYluQJbrpDcgizpllAJpEwMrQRD"
    "I7lDFfpHAqxifpIX6/nT954lWwjLxnQcgIf7O2UK+Pj0LBCWzXQ6VcBZSymlyrJUwrK/TNsU"
    "RWHE1jJC+RPndAl00xSAxvPYSXketJumDMLw195WStZxTOO6B88dbN+p6z1wmSS8FAWrKKKT"
    "5/SD4Kjp0Zmuoohlkuxbfh+PAejk+VHowfYb191D2rSG2xNz1b79fhDQyzI+XJd1HP/P9Gdu"
    "ZzN6WcZWSl6T5GS9lulVXQOw8X2dcj3TzWTC22jEbjjUgmqZ3sznDMKQ68VCC6pl2ho2nmcO"
    "uvF90JwnXPpBUcrYO/0NrarKGFRc4o/6BMuAaAwB5rcdAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
frame = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAABHNCSVQICAgIfAhkiAAAAIhJ"
    "REFUOI3t1LENAyEMheHfd9TswUwMQhIo41FY6QZhAacISlKkSnzFSWfJMjSf9GTJIsuKdy3u"
    "IhBu14t5gqUUAoAqGAoGIvVnsFaIMb7jixky32b3V3/+v9W2ZUDnnFat1TW+qj7j55xJKf0N"
    "ttaAnbZ/oid6BDQA9N591TGGAa4th7n8u6APH3E8/05PRJIAAAAASUVORK5CYII=")

